# Generated by Django 4.1.6 on 2023-02-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productprice',
            new_name='price',
        ),
    ]
